### ISSUE TITLE
Fehler :)

### ISSUE THREAD

**Issue by toedtling** [leit512/homeassistant-verbund-linie-component#1]
Erstmal Danke für das Posten der Komponente 

`2022-10-03 12:15:27.665 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform verbund_linie
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 691, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 777, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 595, in _async_write_ha_state
if (icon := (entry and entry.icon) or self.icon) is not None:
File "/config/custom_components/verbund_linie/sensor.py", line 139, in icon
_LOGGER.debug('next transport is a ' + self._times[0][ATTR_TYPE])
KeyError: 'Type'
2022-10-03 12:15:27.714 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up verbund_linie platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 289, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 691, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 777, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 595, in _async_write_ha_state
if (icon := (entry and entry.icon) or self.icon) is not None:
File "/config/custom_components/verbund_linie/sensor.py", line 139, in icon
_LOGGER.debug('next transport is a ' + self._times[0][ATTR_TYPE])
KeyError: 'Type'`

**Comment by stegmannb** [comment]
Es steht schon lange auf meiner To-Do Liste diese Komponente zu überarbeiten und in einen Zustand zu bringen sie auf HACS veröffentlichen zu können.
Leider kommen ich im Moment nicht dazu sie weiterzuentwickeln.

**Comment by toedtling** [comment]
> Es steht schon lange auf meiner To-Do Liste diese Komponente zu überarbeiten und in einen Zustand zu bringen sie auf HACS veröffentlichen zu können. Leider kommen ich im Moment nicht dazu sie weiterzuentwickeln.

Danke für die Rückmeldung ;) Schade hätte mich gerne mit mehreren Cafe´s bedankt ;)

**Comment by toedtling** [comment]
https://github.com/zacs/ha-gtfs-rt <- villeicht hilft dir das weiter ;)

**Comment by toedtling** [comment]
bzw die Original
https://github.com/phardy/hass-gtfs-realtime
